### PR TITLE
Add support for latin1 encoded source files

### PR DESCRIPTION
**Pull request by tjarvstrand**

### CODE REVIEW

**Comment by tjarvstrand** [comment]
Thanks! Would it be possible to roll a new release? We have some latin-1 encoded source files that we would like to use elvis on :)

**Comment by davecaos** [comment]
Sure! @tjarvstrand

**Comment by davecaos** [comment]
The katana-code [0.0.4 Release](https://github.com/inaka/katana-code/releases/tag/0.0.4) is done.

**Comment by tjarvstrand** [comment]
Thanks!

**Pull request merged**
